### ISSUE TITLE
TypeError: Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by lmerega** [backmeupplz/voicy#93]
Hallo, I cloned this repo on my arm64 Debian server.
The problem is that now I have this error:
TypeError: Cannot read property 'send' of undefined
    at /root/voicy/dist/helpers/urlToText.js:57:16
    at new Promise (<anonymous>)
    at urlToText (/root/voicy/dist/helpers/urlToText.js:47:12)
    at /root/voicy/dist/handlers/handleAudio.js:74:83
    at Generator.next (<anonymous>)
    at fulfilled (/root/voicy/dist/handlers/handleAudio.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {

Any idea?

Thanks

Luca

**Comment by backmeupplz** [comment]
Check if whatever object you use "send" function on at `urlToText.js:47` is not undefined

my guess is that you disabled the cluster api

the easiest way to fix it is to run voicy on a multi-CPU server
